cource/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('accounts.urls')),
    path('course/', include('course.urls', namespace='course'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    path('<int:pk>/',  views.CourseDetailView.as_view(), name='detail'),
    path('<int:pk>/lessons/',  views.CourseLessonsView.as_view(), name='lessons'),
    path('<int:pk>/join/',  views.JoinCourseView.as_view(), name='join'),
    path('lessons/<int:pk>/', views.LessonView.as_view(), name='lesson'),
    path('lessons/<int:pk>/nodes/<int:node>/', views.LessonNodeView.as_view(), name='lesson_node'),
    path('lessons/<int:pk>/finish/', views.FinishLessonView.as_view(), name='lesson_finish')
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
from django.db.models import Count, Q

from course.models import Course


class User(AbstractUser):
    email = models.EmailField(unique=True, verbose_name="Email")
    first_name = models.CharField(max_length=128, verbose_name="First Name", null=True)
    last_name = models.CharField(max_length=128, verbose_name="Last Name", null=True, blank=True)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    username = models.CharField(unique=True, null=True, verbose_name="Username", max_length=128, blank=True)
    courses = models.ManyToManyField('course.Course', blank=True)

    @property
    def full_name(self):
        if self.first_name or self.last_name:
            return '{user.first_name} {user.last_name}'.format(user=self)
        else:
            return self.email

    @property
    def lessons(self):
        return UserLesson.objects.filter(user=self)

    @property
    def not_joined_courses(self):
        courses = Course.objects.filter(is_active=True).exclude(user=self)
        return courses

    @property
    def unfinished_courses(self):
        return Course.objects.annotate(lessons_count=Count('lessons'))\
            .filter(lessons__userlesson__user=self)\
            .exclude(lessons_count=Count('lessons', filter=Q(lessons__userlesson__completed=True)))

    @property
    def completed_courses(self):
        return Course.objects.annotate(lessons_count=Count('lessons'))\
            .filter(lessons__userlesson__user=self,
                    lessons_count=Count('lessons', filter=Q(lessons__userlesson__completed=True)))

    def join_course(self, course):
        self.courses.add(course)
        UserLesson.objects.bulk_create(objs=[
            UserLesson(user=self, lesson=lesson) for lesson in course.lessons.all()
        ])

    def __str__(self):
        return self.full_name


class UserLesson(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    lesson = models.ForeignKey('course.Lesson', on_delete=models.SET_NULL, null=True)
    completed = models.BooleanField(default=False)

course/models.py
from django.db import models


# Create your models here.
from django.http import HttpResponseNotFound
from django.shortcuts import get_object_or_404


class Tutor(models.Model):
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.full_name


class Course(models.Model):
    name = models.CharField(max_length=128, verbose_name='Course name')
    description = models.TextField(verbose_name='Course description')
    tutor = models.ForeignKey(Tutor, on_delete=models.SET_NULL, verbose_name='Tutor', null=True)
    image = models.ImageField(null=True)
    is_active = models.BooleanField(verbose_name='Is Active')

    def __str__(self):
        return self.name


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='lessons')
    name = models.CharField(max_length=128, verbose_name='Lessons name')
    description = models.TextField(verbose_name='Lesson description')

    def get_first_node(self):
        return self.nodes.order_by('number')[0]

    def get_node(self, number):
        return get_object_or_404(LessonNode, lesson=self, number=number)


class LessonNode(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name='nodes')
    number = models.IntegerField()
    text = models.TextField(verbose_name='Text')

    def is_last(self):
        return self.lesson.nodes.order_by('number').last() == self

    def is_first(self):
        return self.lesson.nodes.order_by('number').first() == self

    def get_next_node(self):
        nodes = self.lesson.nodes.order_by('number')
        index = list(nodes.values_list('id', flat=True)).index(self.id)
        if not self.is_last():
            return nodes[index + 1]

    def get_previous_node(self):
        nodes = self.lesson.nodes.order_by('number')
        index = list(nodes.values_list('id', flat=True)).index(self.id)
        if not self.is_first():
            return nodes[index - 1]


class LessonNodeImage(models.Model):
    name = models.CharField(verbose_name="Image name", max_length=256)
    image = models.ImageField(upload_to='lesson_image/')
    lesson_node = models.ForeignKey(LessonNode, on_delete=models.CASCADE, related_name='images')

course/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View
from django.views.generic import DetailView

from accounts.models import UserLesson
from course.models import Course, Lesson


class CourseDetailView(DetailView):
    model = Course
    template_name = 'course/detail.html'


class CourseLessonsView(DetailView):
    model = Course
    template_name = 'course/lesson/lessons.html'

    def get_context_data(self, **kwargs):
        context = super(CourseLessonsView, self).get_context_data(**kwargs)

        context.update({
            'lessons': self.request.user.lessons.filter(lesson__course=self.get_object())
        })
        return context


class JoinCourseView(DetailView):
    model = Course

    def get(self, request, *args, **kwargs):
        course = self.get_object()
        user = request.user
        if user.is_authenticated:
            user.join_course(course)
        return redirect('course:lessons', pk=course.pk)


class LessonView(DetailView):
    model = UserLesson
    template_name = 'course/lesson/lesson.html'


class FinishLessonView(View):

    def get(self, request, pk, **kwargs):
        lesson = UserLesson.objects.filter(user=request.user, lesson_id=pk)[0]
        lesson.completed = True
        lesson.save()
        return redirect('course:lessons', pk=lesson.lesson.course_id)


class LessonNodeView(DetailView):
    model = UserLesson
    template_name = 'course/lesson/lesson_node.html'

    def get(self, request, *args, **kwargs):
        self.node_id = kwargs.pop('node')
        return super(LessonNodeView, self).get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        return self.model.objects.filter(lesson_id=pk, user=self.request.user)[0]

    def get_context_data(self, **kwargs):
        context = super(LessonNodeView, self).get_context_data(**kwargs)
        context.update({
            'node': self.get_object().lesson.get_node(number=self.node_id)
        })
        return context

templates/course/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container" style="margin-top: 50px">
        <div class="row">
            <div class="col-4">
                <img src="{{ object.image.url }}" class="img-fluid" alt="Course image">
            </div>
            <div class="col-8">
                <h3>{{ object.name }}</h3>
                <p> {{ object.description }}</p>

                <ul class="list-group" style="margin: 10px 0">
                  <li class="list-group-item">Lessons: {{ course.lessons.count }}</li>
                  <li class="list-group-item">Students: {{ course.user_set.count }}</li>
                </ul>

                {% if request.user.is_authenticated %}
                    {% if object in request.user.courses.all %}
                        <a class="btn btn-success" role="button" href="{% url 'course:lessons' pk=course.id %}">Go to lessons</a>
                    {% else %}
                        <a class="btn btn-success" role="button" href="{% url 'course:join' pk=course.id %}">Join course</a>
                    {% endif %}
                {% else %}
                    If you wanna join to course, please
                    <a class="btn btn-primary" href="{% url 'sign-in' %}">Sign in</a>
                {% endif %}
            </div>
        </div>
        <div class="row" style="margin-top: 10px">
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        Tutor
                    </div>
                    {% if object.tutor.user.avatar %}
                    <img class="card-img-top" src="{{object.tutor.user.avatar.url}}" alt="User photo">
                    {% endif %}
                    <div class="card-body">
                        <p class="card-text">{{object.tutor.user.full_name}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}