cource/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('accounts.urls')),
    path('course/', include('course.urls', namespace='course'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    path('<int:pk>/',  views.CourseDetailView.as_view(), name='detail'),
    path('<int:pk>/lessons/',  views.CourseLessonsView.as_view(), name='lessons'),
    path('<int:pk>/join/',  views.JoinCourseView.as_view(), name='join'),
    path('lessons/<int:pk>/', views.LessonView.as_view(), name='lesson'),
    path('lessons/<int:pk>/nodes/<int:node>/', views.LessonNodeView.as_view(), name='lesson_node'),
    path('lessons/<int:pk>/finish/', views.FinishLessonView.as_view(), name='lesson_finish')
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView

from course.models import Course


class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get_context_data(self, **kwargs):
        ctx = super(HomeView, self).get_context_data(**kwargs)

        courses = Course.objects.filter(is_active=True)
        ctx.update({
            'courses': courses
        })
        return ctx

templates/home/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        {% if request.user.is_authenticated %}

            {% if request.user.completed_courses.count %}
                <h3>Compeleted courses</h3>
                <div class="card-grid">
                    {% for course in request.user.completed_courses %}
                        <div class="card">
                          <img class="card-img-top" src="{{ course.image.url }}" style="height: 200px" alt="Course image">
                          <div class="card-body">
                            <h5 class="card-title">{{ course.name }}</h5>
                            <p class="card-text">Tutor: {{ course.tutor }}</p>
                            <p class="card-text">{{ course.description|truncatechars:70}}</p>
                            <a href="{% url 'course:detail' pk=course.id %}" class="btn btn-primary">Open</a>
                          </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            {% if request.user.unfinished_courses.count %}
                <h3>Here's your active courses</h3>
                <div class="card-grid">
                    {% for course in request.user.unfinished_courses %}
                        <div class="card">
                          <img class="card-img-top" src="{{ course.image.url }}" style="height: 200px" alt="Course image">
                          <div class="card-body">
                            <h5 class="card-title">{{ course.name }}</h5>
                            <p class="card-text">Tutor: {{ course.tutor }}</p>
                            <p class="card-text">{{ course.description|truncatechars:70}}</p>
                            <a href="{% url 'course:detail' pk=course.id %}" class="btn btn-primary">Open</a>
                          </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            <h3>Available courses</h3>
            <div class="card-grid">
                {% for course in request.user.not_joined_courses %}
                    <div class="card">
                  <img class="card-img-top" src="{{ course.image.url }}" style="height: 200px" alt="Course image">
                  <div class="card-body">
                    <h5 class="card-title">{{ course.name }}</h5>
                    <p class="card-text">Tutor: {{ course.tutor }}</p>
                    <p class="card-text">{{ course.description|truncatechars:70}}</p>
                    <a href="{% url 'course:detail' pk=course.id %}" class="btn btn-primary">Open</a>
                  </div>
                </div>
                {% endfor %}
            </div>

        {% else %}
            <h3>All courses</h3>
            <div class="card-grid">
                {% for course in courses %}
                    <div class="card">
                  <img class="card-img-top" src="{{ course.image.url }}" style="height: 200px" alt="Course image">
                  <div class="card-body">
                    <h5 class="card-title">{{ course.name }}</h5>
                    <p class="card-text">Tutor: {{ course.tutor }}</p>
                    <p class="card-text">{{ course.description|truncatechars:70}}</p>
                    <a href="{% url 'course:detail' pk=course.id %}" class="btn btn-primary">Open</a>
                  </div>
                </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}