cource/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('accounts.urls')),
    path('course/', include('course.urls', namespace='course'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    path('<int:pk>/',  views.CourseDetailView.as_view(), name='detail'),
    path('<int:pk>/lessons/',  views.CourseLessonsView.as_view(), name='lessons'),
    path('<int:pk>/join/',  views.JoinCourseView.as_view(), name='join'),
    path('lessons/<int:pk>/', views.LessonView.as_view(), name='lesson'),
    path('lessons/<int:pk>/nodes/<int:node>/', views.LessonNodeView.as_view(), name='lesson_node'),
    path('lessons/<int:pk>/finish/', views.FinishLessonView.as_view(), name='lesson_finish')
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

course/models.py
from django.db import models


# Create your models here.
from django.http import HttpResponseNotFound
from django.shortcuts import get_object_or_404


class Tutor(models.Model):
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.full_name


class Course(models.Model):
    name = models.CharField(max_length=128, verbose_name='Course name')
    description = models.TextField(verbose_name='Course description')
    tutor = models.ForeignKey(Tutor, on_delete=models.SET_NULL, verbose_name='Tutor', null=True)
    image = models.ImageField(null=True)
    is_active = models.BooleanField(verbose_name='Is Active')

    def __str__(self):
        return self.name


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='lessons')
    name = models.CharField(max_length=128, verbose_name='Lessons name')
    description = models.TextField(verbose_name='Lesson description')

    def get_first_node(self):
        return self.nodes.order_by('number')[0]

    def get_node(self, number):
        return get_object_or_404(LessonNode, lesson=self, number=number)


class LessonNode(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name='nodes')
    number = models.IntegerField()
    text = models.TextField(verbose_name='Text')

    def is_last(self):
        return self.lesson.nodes.order_by('number').last() == self

    def is_first(self):
        return self.lesson.nodes.order_by('number').first() == self

    def get_next_node(self):
        nodes = self.lesson.nodes.order_by('number')
        index = list(nodes.values_list('id', flat=True)).index(self.id)
        if not self.is_last():
            return nodes[index + 1]

    def get_previous_node(self):
        nodes = self.lesson.nodes.order_by('number')
        index = list(nodes.values_list('id', flat=True)).index(self.id)
        if not self.is_first():
            return nodes[index - 1]


class LessonNodeImage(models.Model):
    name = models.CharField(verbose_name="Image name", max_length=256)
    image = models.ImageField(upload_to='lesson_image/')
    lesson_node = models.ForeignKey(LessonNode, on_delete=models.CASCADE, related_name='images')

course/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View
from django.views.generic import DetailView

from accounts.models import UserLesson
from course.models import Course, Lesson


class CourseDetailView(DetailView):
    model = Course
    template_name = 'course/detail.html'


class CourseLessonsView(DetailView):
    model = Course
    template_name = 'course/lesson/lessons.html'

    def get_context_data(self, **kwargs):
        context = super(CourseLessonsView, self).get_context_data(**kwargs)

        context.update({
            'lessons': self.request.user.lessons.filter(lesson__course=self.get_object())
        })
        return context


class JoinCourseView(DetailView):
    model = Course

    def get(self, request, *args, **kwargs):
        course = self.get_object()
        user = request.user
        if user.is_authenticated:
            user.join_course(course)
        return redirect('course:lessons', pk=course.pk)


class LessonView(DetailView):
    model = UserLesson
    template_name = 'course/lesson/lesson.html'


class FinishLessonView(View):

    def get(self, request, pk, **kwargs):
        lesson = UserLesson.objects.filter(user=request.user, lesson_id=pk)[0]
        lesson.completed = True
        lesson.save()
        return redirect('course:lessons', pk=lesson.lesson.course_id)


class LessonNodeView(DetailView):
    model = UserLesson
    template_name = 'course/lesson/lesson_node.html'

    def get(self, request, *args, **kwargs):
        self.node_id = kwargs.pop('node')
        return super(LessonNodeView, self).get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        return self.model.objects.filter(lesson_id=pk, user=self.request.user)[0]

    def get_context_data(self, **kwargs):
        context = super(LessonNodeView, self).get_context_data(**kwargs)
        context.update({
            'node': self.get_object().lesson.get_node(number=self.node_id)
        })
        return context

templates/course/lesson/lesson.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h3>{{ object.lesson.name }}</h3>
        <p>{{ object.lesson.description }}</p>
        <a href="{% url 'course:lesson_node' pk=object.lesson_id node=object.lesson.get_first_node.number %}" class="btn btn-success">Start lesson</a>
    </div>
{% endblock %}

templates/course/lesson/lesson_node.html
{% extends 'base.html' %}

{% block content %}

    <div class="container" style="margin-top: 10px">
        <p>{{ node.text }}</p>

        <div class="row">
            <div class="col">
                <div class="pictures w-50">
                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                      <div class="carousel-inner">
                          {% for image in node.images.all%}
                        <div class="carousel-item {% if forloop.first %} active {% endif %}">
                          <img class="d-block w-100" src="{{ image.image.url }}" alt="">
                            <div class="carousel-caption d-none d-md-block">
                                <p>{{image.name}}</p>
                            </div>
                        </div>
                        {% endfor %}
                      </div>
                      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                      </a>
                      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                      </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row" style="margin: 10px 0">
            <div class="col">
               <div class="actions">
                    {% if not node.is_first %}
                        <a href="{% url 'course:lesson_node' pk=object.lesson_id node=node.get_previous_node.number %}" class="btn btn-primary">Previous</a>
                    {% endif %}
                    {% if node.is_last %}
                        <a href="{% url 'course:lesson_finish' pk=object.lesson_id %}" class="btn btn-success">Finish</a>
                    {% else %}
                        <a href="{% url 'course:lesson_node' pk=object.lesson_id node=node.get_next_node.number %}" class="btn btn-success">Next</a>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>

{% endblock %}

templates/course/lesson/lessons.html
{% extends 'base.html' %}\

{% block content %}
    <div class="container" style="margin-top: 10px">
        <div class="row">
            <div class="col-5">
                <h3> {{ object.name }} </h3>
                <div class="card">
                    <div class="card-header">
                        Tutor
                    </div>
                    {% if object.tutor.user.avatar %}
                    <img class="card-img-top" src="{{object.tutor.user.avatar.url}}" alt="User photo">
                    {% endif %}
                    <div class="card-body">
                        <p class="card-text">{{object.tutor.user.full_name}}</p>
                    </div>
                </div>
            </div>
            <div class="col-7">
                <h3>Lessons</h3>

                <ul class="list-group" style="margin: 10px 0">
                    {% for user_lesson in lessons %}
                        <li class="list-group-item">
                            <a href="{% url 'course:lesson' pk=user_lesson.id %}">{{ user_lesson.lesson.name }}</a>
                            {% if user_lesson.completed %}
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check-circle-fill" fill="#28a745" xmlns="http://www.w3.org/2000/svg">
                                  <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                                </svg>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>

            </div>
        </div>
    </div>
{% endblock %}